name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn build
      - name: s3deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: build/
          bucket: claim.katanainu.com
          bucket-region: us-east-1
          delete-removed: true
          no-cache: true
          private: true
